-- 1. Enable the extension in the default public schema
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

-- 2. Create the table using the standard 'vector' type
CREATE TABLE IF NOT EXISTS public.documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text NOT NULL,
  embedding vector(1024) NOT NULL
);

ALTER TABLE public.documents
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'document.pdf',
  ADD COLUMN IF NOT EXISTS page_number integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS chunk_index integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chunk_id text;

-- Preserve previously ingested rows while giving them stable IDs for future upserts.
UPDATE public.documents
SET chunk_id = 'legacy-' || id::text
WHERE chunk_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS documents_chunk_id_key
  ON public.documents (chunk_id);

CREATE INDEX IF NOT EXISTS documents_embedding_cosine_idx 
ON public.documents 
USING hnsw (embedding vector_cosine_ops);

-- 3. Create the matching RPC function
CREATE OR REPLACE FUNCTION public.match_documents(
  query_embedding vector(1024),
  match_count integer DEFAULT 5 -- Fixed: Changed pg_catalog.integer to standard integer
)
RETURNS TABLE (
  id bigint,                   -- Fixed: Stripped unnecessary pg_catalog prefix
  content text,
  source text,
  page_number integer,
  similarity float8
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_catalog -- Added pg_catalog explicitly to resolve functions securely
AS $$
  SELECT
    d.id,
    d.content,
    d.source,
    d.page_number,
    (1 - (d.embedding <=> query_embedding))::float8 AS similarity
  FROM public.documents AS d
  ORDER BY d.embedding <=> query_embedding
  LIMIT least(greatest(match_count, 1), 10);
$$;

-- 4. Apply strict RPC permissions
REVOKE ALL ON FUNCTION public.match_documents(vector, integer) FROM public;
REVOKE ALL ON FUNCTION public.match_documents(vector, integer) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.match_documents(vector, integer) TO service_role;

NOTIFY pgrst, 'reload schema';

SELECT to_regprocedure('public.match_documents(public.vector,integer)') IS NOT NULL AS function_exists;
