-- Run this migration in the Supabase SQL Editor for the same project used by the app.
create extension if not exists vector with schema extensions;

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  content text not null,
  embedding extensions.vector(1024) not null
);

alter table public.documents
  add column if not exists source text not null default 'document.pdf',
  add column if not exists page_number integer not null default 1,
  add column if not exists chunk_index integer not null default 0,
  add column if not exists chunk_id text;

-- Preserve previously ingested rows while giving them stable IDs for future upserts.
update public.documents
set chunk_id = 'legacy-' || id::text
where chunk_id is null;

create unique index if not exists documents_chunk_id_key
  on public.documents (chunk_id);

create index if not exists documents_embedding_cosine_idx
  on public.documents using hnsw (embedding extensions.vector_cosine_ops);

create or replace function public.match_documents(
  query_embedding extensions.vector(1024),
  match_count integer default 5
)
returns table (
  id bigint,
  content text,
  source text,
  page_number integer,
  similarity double precision
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    d.id,
    d.content,
    d.source,
    d.page_number,
    (1 - (d.embedding OPERATOR(extensions.<=>) query_embedding))::double precision as similarity
  from public.documents as d
  order by d.embedding OPERATOR(extensions.<=>) query_embedding
  limit least(greatest(match_count, 1), 10);
$$;

revoke all on function public.match_documents(extensions.vector, integer) from public;
revoke all on function public.match_documents(extensions.vector, integer) from anon, authenticated;
grant execute on function public.match_documents(extensions.vector, integer) to service_role;

notify pgrst, 'reload schema';
